У завданнях 1-4. Вам наданий простий код на Python, який не відповідає вказівкам PEP8. Ваше завдання — відредагувати код так, аби він відповідав PEP8. Напишіть після редагуванню коду, дотримання яких правил з pep8 ви досягли в відредагованій версі, наприклад
```
- додала пробіли навколо бінарного оператора
- додала два порожні рядки між визначеннями функцій
і тд
```
Також можна зазанчити використані правила коментарями по коду, а не окремим повідомленням.

Відредагований код має виконувати весь той самий функціонал, але бути написаний відповідно до вимог до гарного коду на Python! Не забудьте запустити відредагований код, він має бути робочим.

Завдання 1.

In [1]:
def greet(name):print(f"Hello, {name}")
def add(n1,n2):return n1+n2

x = 5;y = 3
display(greet("John"),add(x,y))

Hello, John

None

8

In [2]:
def greet(name):
    print(f"Hello, {name}")


def add(n1, n2):
    return n1 + n2


x = 5
y = 3

display(greet("John"), add(x, y))

Hello, John

None

8

**Дотримані правила PEP8:**

- додано відступи та перенесення рядків для кращої читабельності;
- додано 2 порожні рядки між визначеннями функцій;
- додано пробіли після ком у параметрах функції;
- додано пробіли навколо бінарного оператора `+`;
- кожну інструкцію винесено на окремий рядок;
- покращено форматування змінних `x` та `y`.

Завдання 2.

In [3]:
from math import *
def calcArea(r):return pi*r**2
def calcCircumference(r):return 2*pi*r

radius=5
print("Area:",calcArea(radius),"Circumference:",calcCircumference(radius))

Area: 78.53981633974483 Circumference: 31.41592653589793

In [4]:
from math import pi


def calc_area(radius):
    return pi * radius**2


def calc_circumference(radius):
    return 2 * pi * radius


radius = 5

print(
    "Area:", 
    calc_area(radius), 
    "Circumference:", 
    calc_circumference(radius)
)

Area: 78.53981633974483 Circumference: 31.41592653589793

**Дотримані правила PEP8:**

- замінено `from math import *` на конкретний імпорт `from math import pi`;
- назви функцій змінено на `snake_case`;
- додано 2 порожні рядки між імпортом і функціями;
- додано 2 порожні рядки між визначеннями функцій;
- додано пробіли навколо операторів `*`, `=`;
- додано пробіли після ком у параметрах функцій і викликах;
- довгий `print()` відформатовано на кілька рядків для кращої читабельності;
- змінну `r` замінено на більш зрозумілу назву `radius`;
- кожна інструкція записана з нового рядка.

Завдання 3.

In [5]:
class animal: pass
class dog(animal):
    def __init__(self,name):
        self.name=name
        self.type='Dog'

In [6]:
class Animal:
    pass


class Dog(Animal):
    def __init__(self, name):
        self.name = name
        self.type = "Dog"

**Дотримані правила PEP8:**

- назви класів змінено на `CamelCase` (`Animal`, `Dog`);
- додано 2 порожні рядки між визначеннями класів;
- додано пробіли після ком у параметрах методу;
- додано пробіли навколо оператора `=`;
- використано подвійні лапки для рядків для єдиного стилю.

Завдання 4.

In [7]:
list=[1,2,3,4,5]
for i in range(len(list)):print(list[i])

1
2
3
4
5

In [8]:
numbers = [1, 2, 3, 4, 5]

for number in numbers:
    print(number)

1
2
3
4
5

**Дотримані правила PEP8:**

- назву змінної `list` (яка впершу чергу є вбудованим типом Python) перейменовано на більш зрозумілу `numbers`;
- додано пробіли після ком у списку;
- кожну інструкцію винесено на окремий рядок;
- додано правильні відступи в циклі;
- спрощено цикл відповідно до рекомендацій Python (`for element in iterable`).

5.У вас є DataFrame df, що представляє результати тестів студентів з математики, англійської мови та історії. Поточний код обчислює середній бал для кожного студента шляхом ітерації за рядками DataFrame за допомогою iterrows().

Ваше завдання полягає в тому, щоб змінити код так, аби уникнути використання iterrows() і замість цього застосувати більш ефективне та читабельне рішення відповідно до правил, озвучених у лекції. Рефакторинг треба зробити лише частині, де рахуються середні, імпорт і визначення датафрейму лишаємо без змін.

In [9]:
import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'David'],
    'math_score': [89, 94, 77, 85],
    'english_score': [92, 88, 79, 85],
    'history_score': [84, 92, 81, 89]
})

In [10]:
averages = []
for _, row in df.iterrows():
    averages.append((row['math_score'] + row['english_score'] + row['history_score']) / 3)

df['average_score'] = averages

In [11]:
# до
df

   student  math_score  english_score  history_score  average_score
0    Alice          89             92             84      88.333333
1      Bob          94             88             92      91.333333
2  Charlie          77             79             81      79.000000
3    David          85             85             89      86.333333

In [12]:
df['average_score'] = df[
    ['math_score', 'english_score', 'history_score']
].mean(axis=1)

In [13]:
# після
df

   student  math_score  english_score  history_score  average_score
0    Alice          89             92             84      88.333333
1      Bob          94             88             92      91.333333
2  Charlie          77             79             81      79.000000
3    David          85             85             89      86.333333

6.У Вас є великий DataFrame df, що представляє транзакції продажу в магазині. Цей DataFrame містить понад 1 мільйон рядків і кілька стовпців, зокрема «product_name», «product_category», «product_price» і «transaction_date».

І «product_name», і «product_category» є рядками, що представляють численні, але обмежені унікальні назви продуктів і категорії відповідно.

Напишіть код для ефективного перетворення стовпців «product_name» і «product_category» на категорійний тип для ефективного використання пам’яті.
Спробуйте вирішити це завдання, мінімізуючи використання пам'яті та зберігаючи читабельність коду. Крім того, виміряйте використання пам’яті до та після перетворення, щоб продемонструвати підвищення ефективності.

Порівняйте кількість памʼяті, яку займає наданий набір даних і новий, створений Вами. В лекції був приклад. В скільки разів менше памʼяті займає новий датафрейм?

In [14]:
import pandas as pd
import numpy as np

np.random.seed(0)

products = ['apple', 'banana', 'cherry', 'dates', 'elderberry']
categories = ['fruit', 'fruit', 'fruit', 'fruit', 'fruit']

N_ROWS = 10**6
df = pd.DataFrame({
    'product_name': np.random.choice(products, N_ROWS),
    'product_category': np.random.choice(categories, N_ROWS),
    'product_price': np.random.uniform(1, 10, N_ROWS),
    'transaction_date': pd.date_range(start='1/1/2000', periods=N_ROWS, freq='h')
})

In [15]:
# переглянемо вихідний вигляд таблиці
df.head()

  product_name product_category  product_price    transaction_date
0   elderberry            fruit       4.696674 2000-01-01 00:00:00
1        apple            fruit       7.176635 2000-01-01 01:00:00
2        dates            fruit       2.507932 2000-01-01 02:00:00
3        dates            fruit       2.079303 2000-01-01 03:00:00
4        dates            fruit       9.482386 2000-01-01 04:00:00

In [16]:
# типи колонок наданого набору даних
df.dtypes

product_name                object
product_category            object
product_price              float64
transaction_date    datetime64[ns]
dtype: object

In [17]:
# кількість пам'яті, яку займає наданий набір даних
memory_before = df.memory_usage(index=False, deep=True).sum()
memory_before

np.int64(125398392)

In [18]:
# створимо копію датафрейму та вкажемо назву потрібних стовпців
df_optimized = df.copy()
categorical_columns = [
    'product_name',
    'product_category'
]

In [19]:
# перетворення стовпців на категоріальний тип  
for col in categorical_columns:
    df_optimized[col] = pd.Categorical(df_optimized[col])

In [20]:
# типи колонок нового набору даних
df_optimized.dtypes

product_name              category
product_category          category
product_price              float64
transaction_date    datetime64[ns]
dtype: object

In [21]:
# кількість пам'яті, яку займає новий набір даних
memory_after = df_optimized.memory_usage(index=False, deep=True).sum()
memory_after

np.int64(18000611)

In [22]:
memory_reduction = memory_before / memory_after

In [23]:
print(f"Новий датафрейм займає в {memory_reduction:.2f} рази менше пам'яті.")

Новий датафрейм займає в 6.97 рази менше пам'яті.

7.В цьому завданні кілька пунктів. Треба виконати усі послідовно.   
    7.1. Завантажте дані у pandas dataframe з файла `ecommerce_data.csv`. Обовʼязково при завантаженні вкажіть параметр `encoding = 'ISO-8859-1'`, без нього буде помилка.  
    7.2. Заповніть пропущені значення в колонці CustomerID на -1 та перетворіть тип цієї колонки на str, адже зараз вона типу float, а це не правильний тип даних для ідентифікатора клієнта.  
    7.3. З допомогою бібліотеки sweetviz побудуйте html звіт, який порівнює дані для країни "Germany" і країни "France". У Вас можуть виникнути багато попереджень (Warning), їх рекомендую вимкнути наступним шматком коду   
    
   
    import warnings

    with warnings.catch_warnings(record=True):
        # your code
    
    
   7.4.Напишіть 5 відмінностей для двох зазначених країн на основі побудованого звіту, без виконання додаткового аналізу іншими інструментами.

In [24]:
# 7.1

data_path = '../Data/ecommerce_data.csv'
data = pd.read_csv(
    data_path,
    encoding = 'ISO-8859-1'
)
type(data)

pandas.core.frame.DataFrame

In [25]:
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [26]:
data.shape

(541909, 8)

In [27]:
data.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [28]:
data['CustomerID'].isna().sum()

np.int64(135080)

In [29]:
data_updated = data.copy()

In [30]:
# 7.2

data_updated['CustomerID'] = (
    data_updated['CustomerID']
    .fillna(-1)
    .astype(str)
)

data_updated['CustomerID'].isna().sum()

np.int64(0)

In [31]:
data_updated.shape

(541909, 8)

In [32]:
data_updated.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID      object
Country         object
dtype: object

In [33]:
!pip install sweetviz

Requirement already satisfied: sweetviz in c:\users\anna\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\users\anna\anaconda3\lib\site-packages (from sweetviz) (2.3.3)
Requirement already satisfied: numpy>=1.16.0 in c:\users\anna\anaconda3\lib\site-packages (from sweetviz) (2.3.5)
Requirement already satisfied: matplotlib>=3.1.3 in c:\users\anna\anaconda3\lib\site-packages (from sweetviz) (3.10.6)
Requirement already satisfied: tqdm>=4.43.0 in c:\users\anna\anaconda3\lib\site-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in c:\users\anna\anaconda3\lib\site-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\anna\anaconda3\lib\site-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in c:\users\anna\anaconda3\lib\site-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anna\anaconda3\lib\site-packages (from jinja2>=2.11.1->sweetviz) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\anna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\anna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\anna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\anna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\anna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\anna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\anna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\anna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anna\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anna\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\anna\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: colorama in c:\users\anna\anaconda3\lib\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)

In [34]:
import sweetviz as sv

In [35]:
germany_data = data_updated[
    data_updated['Country'] == 'Germany'
]

france_data = data_updated[
    data_updated['Country'] == 'France'
]

In [36]:
# 7.3

import warnings

with warnings.catch_warnings(record=True):
    compare_report = sv.compare(
        [germany_data, 'Germany'],
        [france_data, 'France']
    )
    
    compare_report.show_html(
        'germany_vs_france_report.html'
    )

                                             |                                                          | [  0…

Report germany_vs_france_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

**5 відмінностей на основі побудованого звіту:**

1) Для Німеччини кількість замовлень 1 виду товару (згідно з унікальними значеннями `InvoiceNo`) більша на 1 %, ніж для Франції (6 % проти 5 %).
2) Для Франції середня кількість замовлень 1 товару (AVG `Quantity`) дещо вища: 13 проти 12 для Німеччини.
3) В середньому `UnitPrice` для Франції дещо більший: ~5 проти ~4 для Німеччини.
4) Значення `UnitPrice` для Франції більш розсіяні та варіативні за рахунок вищих значень стандартного відхилення (STD) та дисперсії (VAR): 79.9 та 6385 проти 16.5 і 274 для Німеччини.
5) Обидва розподіли значень `UnitPrice` мають сильну правосторонню асиметрію, але для Франції вона значно сильніша через наявність великих значень: асиметрія (SKEW) становить 2574, що майже в 3 рази більше, ніж для Німеччини (866).

8.З допомогою ChatGPT виявіть, чи є та які помилки в наступному коді.  
Попросіть після цього переписати код із дотриманням PEP8. Проаналізуйте результат. Чи справді ChatGPT виправив всі стилістичні помилки? Якщо ні, напишіть йому ще кілька запитів, аби код відповідав вимогам PEP8.  
Вставте фінальну версію коду з чату у ноутбук та запустіть на заданому списку. Має вертатись 50.  
Напишіть, які промпти (інструкції) при зверненні до ChatGPT ви застосували та додайте скріншот(-и) з промптами та відповідями чата.  
Якщо зробили висновки при виконанні цього завдання, то діліться також :)

**ЯК ВСТАВИТИ СКРІНШОТ в Jupyter Notebook** :
1. Створіть нову Markdown клітинку
2. В новоствореній клітинці обираєте в меню Jupyter Notebook Edit -> Insert Image
3. Обираєте картинку
4. В клітинці має зʼявитись текст, який містить картинку. Запустіть клітинку.

Або можна просто перетягнути картинку в Markdown клітинку.

In [37]:
def CalculateVariance(nl):
    sum_list = 0
    for n in nl:
        sum_list = sum_list + n
    mean = sum_list / len(nl)
    sum_squares = 0
    for n in nl:
        sum_squares = sum_squares + n**2
    mean_squares = sum_squares / len(nl)
    return mean_squares

In [38]:
input_list = [75, 80, 85, 90, 95]

In [39]:
# фінальна версія коду з чату

def calculate_variance(numbers):
    if not numbers:
        return None

    mean = sum(numbers) / len(numbers)
    mean_squares = sum(number ** 2 for number in numbers) / len(numbers)

    variance = mean_squares - mean ** 2

    return variance


numbers = [75, 80, 85, 90, 95]

result = calculate_variance(numbers)

print(result)

50.0

Під час звернення до ChatGPT в основному застосовано промпти наступних концепцій (згідно лекційного матеріалу): **Code Review**, **Error Handling** та **Code Consistency**.

Посилання з промптами та відповідями чата: https://chatgpt.com/share/6a0072e1-f680-83eb-b94a-4b7954f20ebc

Під час виконання цього завдання я зрозуміла, що ChatGPT (безкоштовна версія) треба "змушувати" себе перевіряти :)