# Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd
import os
os.listdir()

['.ipynb_checkpoints',
 '9.4 Функції. Продовження.ipynb',
 '9.4 Функціїї. Основи.ipynb',
 '9.5 Класи.ipynb',
 '9.5 Модулі. Винятки.ipynb',
 'Additional HW 1. Базові типи даних. Цикли.ipynb',
 'Additional HW 2. Data structures, loops and functions.ipynb',
 'HW 10.1 Введення у Pandas та NumPy.ipynb',
 'HW 10.2 Oснови роботи з даними у Pandas.ipynb',
 'HW 10.3 Розширені методи обробки даних у Pandas.ipynb',
 'HW 10.4 apply, groupby, pivot_table.ipynb',
 'HW 9.1 Cинтаксис Python.ipynb',
 'HW 9.1 Операції над даними.ipynb',
 'HW 9.2 Control Flow.ipynb',
 'HW 9.2 Словники, набори, кортежі.ipynb',
 'HW 9.2 Списки.ipynb',
 'HW 9.3 Comprehensions.ipynb',
 'HW 9.3 Цикл for.ipynb',
 'HW 9.3 Цикл while.ipynb',
 'supermarket_sales_enriched.csv']

In [2]:
os.listdir('../Data')

['health_insurance_cross_sell_prediction.csv', 'supermarket_sales.csv']

In [3]:
data_path = '../Data/supermarket_sales.csv'
df = pd.read_csv(data_path)
type(df)

pandas.core.frame.DataFrame

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [4]:
df.groupby('Branch')['gross income'].sum().sort_values(ascending=False)

Branch
C    5265.1765
A    5057.1605
B    5057.0320
Name: gross income, dtype: float64

##### Найприбутковішим є філіал супермаркету C.

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [5]:
df[df.Branch == 'C'].groupby('City')['gross income'].sum()

City
Naypyitaw    5265.1765
Name: gross income, dtype: float64

##### В місті Naypyitaw знаходиться філіал з найвищим прибутком.

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [6]:
invoices_by_category = pd.pivot_table(df, index='Branch', columns='Product line', values='Invoice ID', aggfunc='count')
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

##### В філії A купують найбільше товарів з категорії `Home and lifestyle`, тоді як у B - з категорії `Fashion accessories` та `Sports and travel`, а у C - `Food and beverages` та `Fashion accessories`.

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [7]:
print(
    invoices_by_category['Electronic accessories'].idxmax(),
    invoices_by_category['Electronic accessories'].max()
)

A 60

In [8]:
# або

invoices_by_category['Electronic accessories'].sort_values(ascending=False).head(1)

Branch
A    60
Name: Electronic accessories, dtype: int64

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

### 1. Хто в середньому купує більше?

In [9]:
pd.pivot_table(df, index='Customer type', columns='Gender', values='Total', aggfunc='mean')

Gender             Female        Male
Customer type
Member         337.727753  316.985419
Normal         332.233256  305.047581

##### Так як клієнти програми лояльності (`Member`) витрачають більше, то варто інвестувати в залучення нових клієнтів. А з огляду на те, що жінки схильні купувати більше, то треба розвивати таргетований маркетинг.

### 2. Чи суттєво відрізняється попит на різні категорії товарів між містами?

In [10]:
pd.pivot_table(df, index='Product line', columns='City', values='Quantity', aggfunc='sum')

City                    Mandalay  Naypyitaw  Yangon
Product line
Electronic accessories       316        333     322
Fashion accessories          297        342     263
Food and beverages           270        369     313
Health and beauty            320        277     257
Home and lifestyle           295        245     371
Sports and travel            322        265     333

##### Зважаючи на різницю в попиті на різні групи товарів по містах, можна перерозподілити їх складські запаси таким чином, аби зменшити логістичні витрати.

In [11]:
df_updated = pd.read_csv('supermarket_sales_enriched.csv')

### 3. Чи залежить обсяг продажів від часу доби?

In [12]:
pd.pivot_table(df_updated, index='Hour', values='Total', aggfunc='sum').sort_values(by='Total', ascending=False)

           Total
Hour
19    39699.5130
13    34723.2270
10    31421.4810
15    31179.5085
14    30828.3990
11    30377.3295
12    26065.8825
18    26030.3400
16    25226.3235
17    24445.2180
20    22969.5270

##### Отже, чітко прослідковується, що клієнти схильні більше купувати перед роботою, в обідню перерву та після роботи, тому варто оптимізувати графік роботи персоналу таким чином, аби забезпечити комфортне здійснення покупок клієнтами в магазині.